### ISSUE TITLE
Custom HTTP headers per request

### ISSUE THREAD

**Issue by Technius** [Technius/tempget#5]
Sometimes we might need to add additional headers (e.g. OAuth tokens) to access a resource. Like in #4, maybe we can either add headers to each request or specify the headers in a second `credentials.toml`:

```toml
[retrieve]
"foo/bar" = { url = "http://example.com", headers = { Authorization = "Bearer xxxxxxx" } }

[credentials."bar/baz"]
user = "username"
password = "password"
headers = { "Additional_header" = "asdfasdf" }
```
